server:
  port: 8091
logger:
  config: classpath:log4j2.xml
spring:
  profiles:
    active: pg
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd'T'HH:mm:ss
    joda-date-time-format: yyyy-MM-dd'T'HH:mm:ss
  mvc:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    favicon:
      # 关闭favicon.ico
      enabled: false

mybatis-plus:
  # 通配符映射,所有jar下的mapper文件夹下的Mapper.xml结尾的文件
  mapper-locations: classpath*:mapper/*Mapper.xml
  global-config:
    # 数据库相关配置
    db-config:
      # 主键类型 AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID(数字类型唯一ID)", UUID:"全局唯一ID UUID"
      id-type: INPUT
      # 字段策略 IGNORED:"忽略判断", NOT_NULL:"非 NULL 判断"), NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      # 驼峰下划线转换
      column-underline: true
      # 数据库类型
      db-type: POSTGRESQL
  configuration:
    # 开启mybatis驼峰命名
    map-underscore-to-camel-case: true
    # 关闭缓存
    cache-enabled: false
    #开启或者关闭freemarker和thymeleaf的页面缓存
  spring:
    freemarker:
      cache: false
    thymeleaf:
      cache: false
    devtools:
      restart:
        enabled: true
    #需要开启热部署的文件目录
        additional-paths: src/main/java
